### ISSUE TITLE
 Incomplete support for XTerm escape codes

### ISSUE THREAD

**Issue by jepler** [chalk/strip-ansi#10]
Many Unix terminals follow "XTerm escape codes".  I refer to the "rxvt_reference" manpage, available on Debian Jessie as `man 7 urxvt` when the `rxvt-unicode` package is installed:

~~~~
   XTerm Operating System Commands
       "ESC ] Ps;Pt ST"
           Set XTerm Parameters. 8-bit ST: 0x9c, 7-bit ST sequence: ESC \
           (0x1b, 0x5c), backwards compatible terminator BEL (0x07) is also
           accepted. any octet can be escaped by prefixing it with SYN (0x16,
           ^V).

           Ps = 0     Change Icon Name and Window Title to Pt
           Ps = 1     Change Icon Name to Pt
           Ps = 2     Change Window Title to Pt
...
~~~~

So, for example, the sequence `\033]2;example\007` will change the terminal's title to "example" and not use any of the character cells in the terminal itself.

This could be represented as a (non-passing) test:
~~~~
t.is(m('\033]2;example\007'), '')
~~~~
and similar for the ST sequences '\033\\' and '\x9c' though to be honest I'm not sure whether the 8-bit '\x9c' even makes sense in UTF-8 world or can be expressed in javascript unicode strings.since it is only valid as a continuation byte in the UTF-8 encoding; it can probably be ignored.

Note: I originally filed this as https://github.com/sindresorhus/string-width/issues/7 but that author requested that I file it here instead.

**Comment by Qix-** [comment]
Actually this should be filled in `ansi-regex`, but I'll take care of it :)

I'll take a look and adjust if need be! Thanks for letting me know.

**Comment by Qix-** [comment]
Also, yes \x9c can be expressed, though it's not valid UTF-8. Since console styling is usually added after encoding, right before display, then encoding escapes usually isn't an issue since the terminal picks them up anyway.

**Comment by sindresorhus** [comment]
Oops, yeah, sorry. My fault again. Not my day.

**Comment by Qix-** [comment]
Lol no problem :)

**Comment by jepler** [comment]
@sindresorhus @Qix- thank you both for taking the time to get this bug report to the right place.  I'm not very familiar with node/npm norms--is it best conduct for a bug reporter to trace the bug down to the most base module where a problem can be seen, rather than reporting it where they first encountered it?  The deep nesting of modules each with potentially different maintainers (string-width -> strip-ansi -> ansi-regex -> ???) is unfamiliar to me in the rest of my developer experience.

**Comment by sindresorhus** [comment]
> is it best conduct for a bug reporter to trace the bug down to the most base module where a problem can be seen, rather than reporting it where they first encountered it?

Yes, if you're able to do that. It increases the chances of it being fixed as it ends up in the hands of the most relevant people.

**Comment by Qix-** [comment]
FWIW urxvt has some of the strangest escapes I've ever seen. Should be fixable though - definitely not being picked up by ansi-regex. Thanks for the report :)

**Comment by Qix-** [comment]
Fixed :) Thanks for the issue @jepler!
