### ISSUE TITLE
import * as stripAnsi from "strip-ansi";

### ISSUE THREAD

**Issue by timkraut** [chalk/strip-ansi#11]
I tried to import stripAnsi with `import * as stripAnsi from "strip-ansi";` in a TypeScript-Node.js application but this fails with the error message `Module '"/.../node_modules/@types/strip-ansi/index"' resolves to a non-module entity and cannot be imported using this construct.`. The issue seems to be that a function is exported (see e.g. https://github.com/Microsoft/TypeScript/issues/5867#issuecomment-161119689). Would it be possible to change that to something consumable by TypeScript? Or is there any other way I might get this to work?
I know that this module isn't doing much and that I can easily write such a function on my own but I thought maybe other people are going to have the same issue as well so maybe we can try to find a solution for it.

**Comment by kevva** [comment]
`import stripAnsi from 'strip-ansi'`. It only exports a function.

**Comment by timkraut** [comment]
@kevva Thanks for your quick answer! Unfortunately, it doesn't work... `import stripAnsi from "strip-ansi";` results in `strip_ansi_1.default is not a function`. If I import the function using `const stripAnsi = require("strip-ansi");`, it works. Not sure why it doesn't with ES6 imports.

**Comment by kevva** [comment]
Because CommonJS and modules works differently. It's like when you requiring a module in CommonJS where you have to write:

```
const module = require('module').default;
```

**Comment by timkraut** [comment]
I see. Is there any way that I can import this module using ES6 module syntax?

**Comment by sindresorhus** [comment]
We're not going to change just because you use TypeScript. If you use TypeScript it's up to you to figure out how to use packages with it. This module is exported exactly like most npm packages.
