### ISSUE TITLE
ie11 does not work

### ISSUE THREAD

**Issue by beans9** [chalk/strip-ansi#18]
It does not work on ie11.
It can be used after modifying the arrow function to a general function.

`
module.exports = input => typeof input === 'string' ? input.replace(ansiRegex(), '') : input;
`
work after modified 
`
module.exports = function(input) {
  return typeof input === 'string' ? input.replace(ansiRegex(), '') : input;
}
`

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
