### ISSUE TITLE
es6 code not supported in some browsers

### ISSUE THREAD

**Issue by hoperyy** [chalk/strip-ansi#22]
Can you support es5. 

Some library like ''string-width" depends on it so I cannot modifiy the es6 code directly.

Thanks!

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
