### ISSUE TITLE
Add notes about non-esm version in readme

### ISSUE THREAD

**Issue by peey** [chalk/strip-ansi#42]
ESM breaks some build configurations, e.g. I was getting the following with a ts-node based configuration all of the sudden (and it doesn't even point to `strip-ansi`, it points to my own typescript files! only difference being if I'm importing strip-ansi or not)

```
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"
```

Consequently, I've had to revert to `3.0.0` for the meanwhile.

I'd request that a note mentioning the latest non-ESM version should be present in the documentation so that we can still work with the library until build systems are upgraded to acommodate ESM.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

The package is clearly marked as ESM: https://github.com/chalk/strip-ansi/blob/2b8c961e75760059699373f9a69101065c3ded3a/package.json#L13 I don't see the need to document the fact in the readme.

**Comment by peey** [comment]
It's clear that the package is ESM. The request was for **the latest non-ESM version** to be documented.

**Comment by risenforces** [comment]
This is a very stupid decision as a library maintainer to not support other formats. Why we can use chalk without ESM, but not this package? I'm just losing a lot of time copying this **** locally

Thanks for the nice library, @sindresorhus! I definitely support you..

**Comment by Qix-** [comment]
Comments are getting rude and insulting, going to lock this. There's nothing further actionable here.
