### ISSUE TITLE
release github release 

### ISSUE THREAD

**Issue by jimmywarting** [chalk/strip-ansi#46]

**Comment by Qix-** [comment]
Hey Jimmy, do you mean the Github releases information? The latest version is published on npm and tagged here, unless I missing something.

**Comment by jimmywarting** [comment]
strip-ansi on npm says latest version is v7
here on github it says latest version is 6.0.1

it's true that it says that there exist a v7 tag but it's not released on github

![image](https://user-images.githubusercontent.com/1148376/153657261-da3ca925-251f-4e3d-857d-35c708b73c6b.png)

**Comment by sindresorhus** [comment]
Fixed
