### ISSUE TITLE
I didnt find jest-junit  latest version updated with latest strip ansi 7.0.1

### ISSUE THREAD

**Issue by suj123j** [chalk/strip-ansi#48]
Hi Team,
Today for strip ansi the latest version is 7.0.1 with no vulnerabilities.the jest-junit version with 16.0.0 is not updated with these dependency strip ansi 7.0.1. Can you help me here ??

![strip](https://user-images.githubusercontent.com/131941646/236115214-fde0912f-8b03-46e8-8ef0-1d2fbc33b864.PNG)

**Comment by sindresorhus** [comment]
This would be a question for `jest-junit`.
