### ISSUE TITLE
License not readable

### ISSUE THREAD

**Issue by victorlmneves** [chalk/strip-ansi#50]
Hi
I'm working on a project where a package uses your library
Now that we are testing the pipeline we have started getting errors related to the package license file

```js
[ERROR] The IQ Server reports policy failing due to 
Policy(License-None) [
 Component(displayName=strip-ansi-cjs : 6.0.1, hash=849ff8d01283d89e19c0) [
  Constraint(Contact Sonatype Support - declared license issue: Not Provided) [License is 'Not Supported' because: Found 'Not Supported' license, on condition 0, License is 'Not Provided' because: Found 'Not Provided' license, on condition 0] ]]
[ERROR] The IQ Server reports policy failing due to 
Policy(License-None) [
 Component(displayName=string-width-cjs : 4.2.3, hash=e621da8847ceb2f46d3f) [
  Constraint(Contact Sonatype Support - declared license issue: Not Provided) [License is 'Not Supported' because: Found 'Not Supported' license, on condition 0, License is 'Not Provided' because: Found 'Not Provided' license, on condition 0] ]]
[ERROR] The IQ Server reports policy failing due to 
Policy(License-None) [
 Component(displayName=wrap-ansi-cjs : 7.0.0, hash=feb65f52a9f9713d5c12) [
  Constraint(Contact Sonatype Support - declared license issue: Not Provided) [License is 'Not Supported' because: Found 'Not Supported' license, on condition 0, License is 'Not Provided' because: Found 'Not Provided' license, on condition 0] ]]
[WARN] The IQ Server reports policy warning due to 
```

I have used Gemini to see if there was any problem with the license file and got this answer
![image](https://github.com/chalk/strip-ansi/assets/17341789/caacf44e-d3d1-4590-962b-57df235a1458)

While asking for example to check the one from Vue, I got the answer
![image](https://github.com/chalk/strip-ansi/assets/17341789/8bbb2b6f-3ca8-47ed-a56c-7b336abbeb91)

Thanks

**Comment by Qix-** [comment]
Sorry, there's nothing actionable here. Seems like a problem with the tooling you're using. Our license is a normal text file and we even have the license identifier in the package.json as a hint. Github picks it up just fine.

![image](https://github.com/chalk/strip-ansi/assets/885648/41c8e126-e530-4936-8f00-2f1f8173c1cb)

**Comment by Qix-** [comment]
Not sure 🙃 can you find something wrong with our license file? I don't know what NexusIQ is so it's probably best to ask them.

**Comment by victorlmneves** [comment]
NexusIQ provides intelligence on open-source components used within your applications, and associated metadata, such as security vulnerabilities and licenses.
We had a similar issue in the past from another library and in that case, they didn't have any license file available in the repo
I just reported because when I tried to find if it was something related to the content of the license file Gemini complained about not being able to access it and doing the same test for the Vue license there was no problem
And since I see it complaining on multiple versions, I don't know if there was a problem when the file was created or something else.
I can also ask in the company if they can get some feedback from NexusIQ about this
